{
 "title": "Node Daskboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Node Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100"
    }
   ]
  },
  {
   "title": "Node CPU Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node:node_cpu_utilisation:avg1m",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)/node:node_memory_bytes_total:sum",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_disk_io_now", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node Net Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node:node_net_utilisation:sum_irate",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}