kind: Pod
apiVersion: v1
metadata:
  name: test-pod-rbd
  namespace: rook-ceph
  labels:
    test-rbd: "true"
spec:
  containers:
  - name: test-pod
    image: alpine:latest
    command:
    - "apk add xfsprogs"
    - "ls /usr/sbin | grep mkfs"
    volumeMounts:
    - name: data
      mountPath: "/mnt"
      readOnly: false
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: testclaim