kind: Pod
apiVersion: v1
metadata:
  name: test-pod-rbd2
  namespace: rook-ceph
  labels:
    test-rbd2: "true"
spec:
  containers:
  - name: test-pod2
    image: busybox:latest
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "trap exit TERM; while true; do sleep 1; done"
    volumeMounts:
    - name: data
      mountPath: "/mnt"
      readOnly: false
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: testclaim2